### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by stephenyaoshun** [BelinChung/cordova-plugin-weibo#1]
window.weibo.isInstalled怎么使用，安装了就调用onsucess吗？

**Comment by BelinChung** [comment]
`weibo.init(xx,xx);` 初始化后

```
weibo.isInstalled(funtion(status){
    console.log(status)
});
```

你试试，我没有测过这个API，看正不正确

**Comment by fengfangqian** [comment]
@BelinChung 我试了，不管手机上有没有安装新浪微博success函数都会执行，我现在要判断新浪微博是否安装了该怎么使用该函数

**Comment by stephenyaoshun** [comment]
@BelinChung ok通过判断status的值可知是否安装有微博客户端，3q

**Comment by stephenyaoshun** [comment]
@BelinChung 不过貌似没安装客户端调用页面的时候貌似有问题，会一直反复的登录不上，然后报这个错误
04-23 22:12:18.436: W/ActivityManager(725): getTasks: caller 10090 does not hold GET_TASKS; limiting output

**Comment by BelinChung** [comment]
我这边测试是正常的哦？要不你看看debug进去？

**Comment by stephenyaoshun** [comment]
@BelinChung  hi你所访问的站点微博认证失败，错误号21322 代码如下，还有个疑问为啥我没有用到secret，还是说你这个方式是老的，新浪更新了？
window.weibo.init('443866145','http://www.xiaoqianbao.cn.com/oauth2/default.html');
        window.weibo.login(function (res) {
            alert(res);
            console.log(res);
        });
        window.weibo.share({
            type: 'image',
            data: 'http://www.xiaoqianbao.cn.com/xqb.jpg',
            text: '土豪喊你抢红包啦，来晚了就木有啰！下载小钱包，用手机做任务就能换Q币，话费，支付宝提现,赶紧来试试吧！'
        },function(res){
            //console.log(res);
        });

**Comment by BelinChung** [comment]
@fengfangqian 客户端存放 secret 容易被人反编译拿到，所以现在SDK的验证都是通过包签名
请确保 callback url 和开发平台里面填写的 callback url 一致即可

其他各问题，请向官方SDK开发团队咨询

**Comment by stephenyaoshun** [comment]
这个也算原生调用，根据官方文档callback_url可以填写他们默认的https://api.weibo.com/oauth2/default.html但是现在一调就崩溃了错误日志如下
window.weibo.init('443866145','https://api.weibo.com/oauth2/default.html');

05-27 11:39:39.829: W/System.err(6901): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sina/weibo/sdk/auth/AuthInfo;
05-27 11:39:39.829: W/System.err(6901):     at com.hiliaox.Weibo.init(Weibo.java:112)
05-27 11:39:39.829: W/System.err(6901):     at com.hiliaox.Weibo.execute(Weibo.java:55)
05-27 11:39:39.829: W/System.err(6901):     at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
05-27 11:39:39.829: W/System.err(6901):     at org.apache.cordova.PluginManager.exec(PluginManager.java:151)
05-27 11:39:39.829: W/System.err(6901):     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:63)
05-27 11:39:39.829: W/System.err(6901):     at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
05-27 11:39:39.829: W/System.err(6901):     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
05-27 11:39:39.829: W/System.err(6901):     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
05-27 11:39:39.829: W/System.err(6901):     at android.os.Handler.dispatchMessage(Handler.java:102)
05-27 11:39:39.829: W/System.err(6901):     at android.os.Looper.loop(Looper.java:135)
05-27 11:39:39.829: W/System.err(6901):     at android.os.HandlerThread.run(HandlerThread.java:61)
05-27 11:39:39.829: W/System.err(6901): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sina.weibo.sdk.auth.AuthInfo" on path: DexPathList[[zip file "/data/app/com.juyou.xiaoqianbao-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
05-27 11:39:39.829: W/System.err(6901):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-27 11:39:39.830: W/System.err(6901):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
05-27 11:39:39.830: W/System.err(6901):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
05-27 11:39:39.830: W/System.err(6901):     ... 11 more
05-27 11:39:39.830: W/System.err(6901):     Suppressed: java.lang.ClassNotFoundException: com.sina.weibo.sdk.auth.AuthInfo
05-27 11:39:39.830: W/System.err(6901):         at java.lang.Class.classForName(Native Method)
05-27 11:39:39.830: W/System.err(6901):         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
05-27 11:39:39.830: W/System.err(6901):         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
05-27 11:39:39.830: W/System.err(6901):         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
05-27 11:39:39.830: W/System.err(6901):         ... 12 more
05-27 11:39:39.830: W/System.err(6901):     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
