### ISSUE TITLE
亲爱的牛逼神武的楼主

### ISSUE THREAD

**Issue by yangheng** [BelinChung/cordova-plugin-weibo#6]
IOS URL identifier 应该是 weibosdk
并且 呢 需要在 ios9 里面加入白名单  weibosdk  楼主更新一下 文档吧

**Comment by BelinChung** [comment]
非常感谢！
不过作为 Weibo SDK 第三方扩展，所有的基础文档和接口还是跟官方文档一模一样的
就像你呀，不是也去翻了官方文档了嘛。

**Comment by BelinChung** [comment]
新版已更新文档
